### ISSUE TITLE
Write Plan Guidance

### ISSUE THREAD

**Issue by JEK-III** [JEK-III/tracking#9]
- [ ] plan guidance will be per question
- [ ] add question label to guidance panel
- [x] add suggested answer between question and answer box
- [ ] add spec that the guidance box should remember its state for each question; when a user clicks away and clicks back, it should be in the state they left it.
- [ ] the "Types of data" question box is cut off at the bottom– fix that.
